// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/site.proto

package com.akaxin.proto.core;

public final class SiteProto {
  private SiteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SiteInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.SiteInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *站点ip
     * </pre>
     *
     * <code>optional string site_address = 1;</code>
     */
    java.lang.String getSiteAddress();
    /**
     * <pre>
     *站点ip
     * </pre>
     *
     * <code>optional string site_address = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteAddressBytes();

    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional int32 site_port = 2;</code>
     */
    int getSitePort();

    /**
     * <pre>
     *站点名称
     * </pre>
     *
     * <code>optional string site_name = 3;</code>
     */
    java.lang.String getSiteName();
    /**
     * <pre>
     *站点名称
     * </pre>
     *
     * <code>optional string site_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getSiteNameBytes();

    /**
     * <pre>
     *站点logo
     * </pre>
     *
     * <code>optional string site_logo = 4;</code>
     */
    java.lang.String getSiteLogo();
    /**
     * <pre>
     *站点logo
     * </pre>
     *
     * <code>optional string site_logo = 4;</code>
     */
    com.google.protobuf.ByteString
        getSiteLogoBytes();

    /**
     * <pre>
     *站点介绍
     * </pre>
     *
     * <code>optional string site_introduction = 5;</code>
     */
    java.lang.String getSiteIntroduction();
    /**
     * <pre>
     *站点介绍
     * </pre>
     *
     * <code>optional string site_introduction = 5;</code>
     */
    com.google.protobuf.ByteString
        getSiteIntroductionBytes();
  }
  /**
   * <pre>
   *需要推荐的站点信息
   * </pre>
   *
   * Protobuf type {@code core.SiteInfo}
   */
  public  static final class SiteInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.SiteInfo)
      SiteInfoOrBuilder {
    // Use SiteInfo.newBuilder() to construct.
    private SiteInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SiteInfo() {
      siteAddress_ = "";
      sitePort_ = 0;
      siteName_ = "";
      siteLogo_ = "";
      siteIntroduction_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SiteInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              siteAddress_ = s;
              break;
            }
            case 16: {

              sitePort_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              siteName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              siteLogo_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              siteIntroduction_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.core.SiteProto.internal_static_core_SiteInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.core.SiteProto.internal_static_core_SiteInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.core.SiteProto.SiteInfo.class, com.akaxin.proto.core.SiteProto.SiteInfo.Builder.class);
    }

    public static final int SITE_ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object siteAddress_;
    /**
     * <pre>
     *站点ip
     * </pre>
     *
     * <code>optional string site_address = 1;</code>
     */
    public java.lang.String getSiteAddress() {
      java.lang.Object ref = siteAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *站点ip
     * </pre>
     *
     * <code>optional string site_address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteAddressBytes() {
      java.lang.Object ref = siteAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_PORT_FIELD_NUMBER = 2;
    private int sitePort_;
    /**
     * <pre>
     *站点地址
     * </pre>
     *
     * <code>optional int32 site_port = 2;</code>
     */
    public int getSitePort() {
      return sitePort_;
    }

    public static final int SITE_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object siteName_;
    /**
     * <pre>
     *站点名称
     * </pre>
     *
     * <code>optional string site_name = 3;</code>
     */
    public java.lang.String getSiteName() {
      java.lang.Object ref = siteName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *站点名称
     * </pre>
     *
     * <code>optional string site_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSiteNameBytes() {
      java.lang.Object ref = siteName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_LOGO_FIELD_NUMBER = 4;
    private volatile java.lang.Object siteLogo_;
    /**
     * <pre>
     *站点logo
     * </pre>
     *
     * <code>optional string site_logo = 4;</code>
     */
    public java.lang.String getSiteLogo() {
      java.lang.Object ref = siteLogo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteLogo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *站点logo
     * </pre>
     *
     * <code>optional string site_logo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSiteLogoBytes() {
      java.lang.Object ref = siteLogo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteLogo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_INTRODUCTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object siteIntroduction_;
    /**
     * <pre>
     *站点介绍
     * </pre>
     *
     * <code>optional string site_introduction = 5;</code>
     */
    public java.lang.String getSiteIntroduction() {
      java.lang.Object ref = siteIntroduction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteIntroduction_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *站点介绍
     * </pre>
     *
     * <code>optional string site_introduction = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSiteIntroductionBytes() {
      java.lang.Object ref = siteIntroduction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteIntroduction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSiteAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, siteAddress_);
      }
      if (sitePort_ != 0) {
        output.writeInt32(2, sitePort_);
      }
      if (!getSiteNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, siteName_);
      }
      if (!getSiteLogoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, siteLogo_);
      }
      if (!getSiteIntroductionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, siteIntroduction_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSiteAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, siteAddress_);
      }
      if (sitePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sitePort_);
      }
      if (!getSiteNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, siteName_);
      }
      if (!getSiteLogoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, siteLogo_);
      }
      if (!getSiteIntroductionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, siteIntroduction_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.core.SiteProto.SiteInfo)) {
        return super.equals(obj);
      }
      com.akaxin.proto.core.SiteProto.SiteInfo other = (com.akaxin.proto.core.SiteProto.SiteInfo) obj;

      boolean result = true;
      result = result && getSiteAddress()
          .equals(other.getSiteAddress());
      result = result && (getSitePort()
          == other.getSitePort());
      result = result && getSiteName()
          .equals(other.getSiteName());
      result = result && getSiteLogo()
          .equals(other.getSiteLogo());
      result = result && getSiteIntroduction()
          .equals(other.getSiteIntroduction());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SITE_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getSiteAddress().hashCode();
      hash = (37 * hash) + SITE_PORT_FIELD_NUMBER;
      hash = (53 * hash) + getSitePort();
      hash = (37 * hash) + SITE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSiteName().hashCode();
      hash = (37 * hash) + SITE_LOGO_FIELD_NUMBER;
      hash = (53 * hash) + getSiteLogo().hashCode();
      hash = (37 * hash) + SITE_INTRODUCTION_FIELD_NUMBER;
      hash = (53 * hash) + getSiteIntroduction().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.core.SiteProto.SiteInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.core.SiteProto.SiteInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.core.SiteProto.SiteInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *需要推荐的站点信息
     * </pre>
     *
     * Protobuf type {@code core.SiteInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.SiteInfo)
        com.akaxin.proto.core.SiteProto.SiteInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.core.SiteProto.internal_static_core_SiteInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.core.SiteProto.internal_static_core_SiteInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.core.SiteProto.SiteInfo.class, com.akaxin.proto.core.SiteProto.SiteInfo.Builder.class);
      }

      // Construct using com.akaxin.proto.core.SiteProto.SiteInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        siteAddress_ = "";

        sitePort_ = 0;

        siteName_ = "";

        siteLogo_ = "";

        siteIntroduction_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.core.SiteProto.internal_static_core_SiteInfo_descriptor;
      }

      public com.akaxin.proto.core.SiteProto.SiteInfo getDefaultInstanceForType() {
        return com.akaxin.proto.core.SiteProto.SiteInfo.getDefaultInstance();
      }

      public com.akaxin.proto.core.SiteProto.SiteInfo build() {
        com.akaxin.proto.core.SiteProto.SiteInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.core.SiteProto.SiteInfo buildPartial() {
        com.akaxin.proto.core.SiteProto.SiteInfo result = new com.akaxin.proto.core.SiteProto.SiteInfo(this);
        result.siteAddress_ = siteAddress_;
        result.sitePort_ = sitePort_;
        result.siteName_ = siteName_;
        result.siteLogo_ = siteLogo_;
        result.siteIntroduction_ = siteIntroduction_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.core.SiteProto.SiteInfo) {
          return mergeFrom((com.akaxin.proto.core.SiteProto.SiteInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.core.SiteProto.SiteInfo other) {
        if (other == com.akaxin.proto.core.SiteProto.SiteInfo.getDefaultInstance()) return this;
        if (!other.getSiteAddress().isEmpty()) {
          siteAddress_ = other.siteAddress_;
          onChanged();
        }
        if (other.getSitePort() != 0) {
          setSitePort(other.getSitePort());
        }
        if (!other.getSiteName().isEmpty()) {
          siteName_ = other.siteName_;
          onChanged();
        }
        if (!other.getSiteLogo().isEmpty()) {
          siteLogo_ = other.siteLogo_;
          onChanged();
        }
        if (!other.getSiteIntroduction().isEmpty()) {
          siteIntroduction_ = other.siteIntroduction_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.core.SiteProto.SiteInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.core.SiteProto.SiteInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object siteAddress_ = "";
      /**
       * <pre>
       *站点ip
       * </pre>
       *
       * <code>optional string site_address = 1;</code>
       */
      public java.lang.String getSiteAddress() {
        java.lang.Object ref = siteAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *站点ip
       * </pre>
       *
       * <code>optional string site_address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteAddressBytes() {
        java.lang.Object ref = siteAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *站点ip
       * </pre>
       *
       * <code>optional string site_address = 1;</code>
       */
      public Builder setSiteAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点ip
       * </pre>
       *
       * <code>optional string site_address = 1;</code>
       */
      public Builder clearSiteAddress() {
        
        siteAddress_ = getDefaultInstance().getSiteAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点ip
       * </pre>
       *
       * <code>optional string site_address = 1;</code>
       */
      public Builder setSiteAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteAddress_ = value;
        onChanged();
        return this;
      }

      private int sitePort_ ;
      /**
       * <pre>
       *站点地址
       * </pre>
       *
       * <code>optional int32 site_port = 2;</code>
       */
      public int getSitePort() {
        return sitePort_;
      }
      /**
       * <pre>
       *站点地址
       * </pre>
       *
       * <code>optional int32 site_port = 2;</code>
       */
      public Builder setSitePort(int value) {
        
        sitePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点地址
       * </pre>
       *
       * <code>optional int32 site_port = 2;</code>
       */
      public Builder clearSitePort() {
        
        sitePort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object siteName_ = "";
      /**
       * <pre>
       *站点名称
       * </pre>
       *
       * <code>optional string site_name = 3;</code>
       */
      public java.lang.String getSiteName() {
        java.lang.Object ref = siteName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *站点名称
       * </pre>
       *
       * <code>optional string site_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSiteNameBytes() {
        java.lang.Object ref = siteName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *站点名称
       * </pre>
       *
       * <code>optional string site_name = 3;</code>
       */
      public Builder setSiteName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点名称
       * </pre>
       *
       * <code>optional string site_name = 3;</code>
       */
      public Builder clearSiteName() {
        
        siteName_ = getDefaultInstance().getSiteName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点名称
       * </pre>
       *
       * <code>optional string site_name = 3;</code>
       */
      public Builder setSiteNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object siteLogo_ = "";
      /**
       * <pre>
       *站点logo
       * </pre>
       *
       * <code>optional string site_logo = 4;</code>
       */
      public java.lang.String getSiteLogo() {
        java.lang.Object ref = siteLogo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteLogo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *站点logo
       * </pre>
       *
       * <code>optional string site_logo = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSiteLogoBytes() {
        java.lang.Object ref = siteLogo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteLogo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *站点logo
       * </pre>
       *
       * <code>optional string site_logo = 4;</code>
       */
      public Builder setSiteLogo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteLogo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点logo
       * </pre>
       *
       * <code>optional string site_logo = 4;</code>
       */
      public Builder clearSiteLogo() {
        
        siteLogo_ = getDefaultInstance().getSiteLogo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点logo
       * </pre>
       *
       * <code>optional string site_logo = 4;</code>
       */
      public Builder setSiteLogoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteLogo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object siteIntroduction_ = "";
      /**
       * <pre>
       *站点介绍
       * </pre>
       *
       * <code>optional string site_introduction = 5;</code>
       */
      public java.lang.String getSiteIntroduction() {
        java.lang.Object ref = siteIntroduction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteIntroduction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *站点介绍
       * </pre>
       *
       * <code>optional string site_introduction = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSiteIntroductionBytes() {
        java.lang.Object ref = siteIntroduction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteIntroduction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *站点介绍
       * </pre>
       *
       * <code>optional string site_introduction = 5;</code>
       */
      public Builder setSiteIntroduction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteIntroduction_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点介绍
       * </pre>
       *
       * <code>optional string site_introduction = 5;</code>
       */
      public Builder clearSiteIntroduction() {
        
        siteIntroduction_ = getDefaultInstance().getSiteIntroduction();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点介绍
       * </pre>
       *
       * <code>optional string site_introduction = 5;</code>
       */
      public Builder setSiteIntroductionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteIntroduction_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:core.SiteInfo)
    }

    // @@protoc_insertion_point(class_scope:core.SiteInfo)
    private static final com.akaxin.proto.core.SiteProto.SiteInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.core.SiteProto.SiteInfo();
    }

    public static com.akaxin.proto.core.SiteProto.SiteInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SiteInfo>
        PARSER = new com.google.protobuf.AbstractParser<SiteInfo>() {
      public SiteInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SiteInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SiteInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SiteInfo> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.core.SiteProto.SiteInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_SiteInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_SiteInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017core/site.proto\022\004core\"t\n\010SiteInfo\022\024\n\014s" +
      "ite_address\030\001 \001(\t\022\021\n\tsite_port\030\002 \001(\005\022\021\n\t" +
      "site_name\030\003 \001(\t\022\021\n\tsite_logo\030\004 \001(\t\022\031\n\021si" +
      "te_introduction\030\005 \001(\tB\"\n\025com.akaxin.prot" +
      "o.coreB\tSiteProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_core_SiteInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_SiteInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_SiteInfo_descriptor,
        new java.lang.String[] { "SiteAddress", "SitePort", "SiteName", "SiteLogo", "SiteIntroduction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
