// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_phone_applyCode.proto

package com.akaxin.proto.platform;

public final class ApiPhoneApplyCodeProto {
  private ApiPhoneApplyCodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiPhoneApplyCodeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPhoneApplyCodeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional string user_id = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional string user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * Protobuf type {@code platform.ApiPhoneApplyCodeRequest}
   */
  public  static final class ApiPhoneApplyCodeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiPhoneApplyCodeRequest)
      ApiPhoneApplyCodeRequestOrBuilder {
    // Use ApiPhoneApplyCodeRequest.newBuilder() to construct.
    private ApiPhoneApplyCodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPhoneApplyCodeRequest() {
      userId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiPhoneApplyCodeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest.class, com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional string user_id = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional string user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest other = (com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiPhoneApplyCodeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPhoneApplyCodeRequest)
        com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest.class, com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeRequest_descriptor;
      }

      public com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest build() {
        com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest buildPartial() {
        com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest result = new com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest(this);
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest) {
          return mergeFrom((com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest other) {
        if (other == com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string user_id = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string user_id = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional string user_id = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiPhoneApplyCodeRequest)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiPhoneApplyCodeRequest)
    private static final com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest();
    }

    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPhoneApplyCodeRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiPhoneApplyCodeRequest>() {
      public ApiPhoneApplyCodeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiPhoneApplyCodeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPhoneApplyCodeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPhoneApplyCodeRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiPhoneApplyCodeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPhoneApplyCodeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *平台允许站点获取手机号code
     * </pre>
     *
     * <code>optional string phone_code = 1;</code>
     */
    java.lang.String getPhoneCode();
    /**
     * <pre>
     *平台允许站点获取手机号code
     * </pre>
     *
     * <code>optional string phone_code = 1;</code>
     */
    com.google.protobuf.ByteString
        getPhoneCodeBytes();

    /**
     * <pre>
     *code有效时间，单位s
     * </pre>
     *
     * <code>optional int32 expire_time = 2;</code>
     */
    int getExpireTime();
  }
  /**
   * Protobuf type {@code platform.ApiPhoneApplyCodeResponse}
   */
  public  static final class ApiPhoneApplyCodeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiPhoneApplyCodeResponse)
      ApiPhoneApplyCodeResponseOrBuilder {
    // Use ApiPhoneApplyCodeResponse.newBuilder() to construct.
    private ApiPhoneApplyCodeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPhoneApplyCodeResponse() {
      phoneCode_ = "";
      expireTime_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiPhoneApplyCodeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneCode_ = s;
              break;
            }
            case 16: {

              expireTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse.class, com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse.Builder.class);
    }

    public static final int PHONE_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object phoneCode_;
    /**
     * <pre>
     *平台允许站点获取手机号code
     * </pre>
     *
     * <code>optional string phone_code = 1;</code>
     */
    public java.lang.String getPhoneCode() {
      java.lang.Object ref = phoneCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *平台允许站点获取手机号code
     * </pre>
     *
     * <code>optional string phone_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneCodeBytes() {
      java.lang.Object ref = phoneCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRE_TIME_FIELD_NUMBER = 2;
    private int expireTime_;
    /**
     * <pre>
     *code有效时间，单位s
     * </pre>
     *
     * <code>optional int32 expire_time = 2;</code>
     */
    public int getExpireTime() {
      return expireTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPhoneCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, phoneCode_);
      }
      if (expireTime_ != 0) {
        output.writeInt32(2, expireTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPhoneCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, phoneCode_);
      }
      if (expireTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, expireTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse other = (com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse) obj;

      boolean result = true;
      result = result && getPhoneCode()
          .equals(other.getPhoneCode());
      result = result && (getExpireTime()
          == other.getExpireTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PHONE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneCode().hashCode();
      hash = (37 * hash) + EXPIRE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getExpireTime();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiPhoneApplyCodeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPhoneApplyCodeResponse)
        com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse.class, com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        phoneCode_ = "";

        expireTime_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.internal_static_platform_ApiPhoneApplyCodeResponse_descriptor;
      }

      public com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse build() {
        com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse buildPartial() {
        com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse result = new com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse(this);
        result.phoneCode_ = phoneCode_;
        result.expireTime_ = expireTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse) {
          return mergeFrom((com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse other) {
        if (other == com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse.getDefaultInstance()) return this;
        if (!other.getPhoneCode().isEmpty()) {
          phoneCode_ = other.phoneCode_;
          onChanged();
        }
        if (other.getExpireTime() != 0) {
          setExpireTime(other.getExpireTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object phoneCode_ = "";
      /**
       * <pre>
       *平台允许站点获取手机号code
       * </pre>
       *
       * <code>optional string phone_code = 1;</code>
       */
      public java.lang.String getPhoneCode() {
        java.lang.Object ref = phoneCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *平台允许站点获取手机号code
       * </pre>
       *
       * <code>optional string phone_code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneCodeBytes() {
        java.lang.Object ref = phoneCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *平台允许站点获取手机号code
       * </pre>
       *
       * <code>optional string phone_code = 1;</code>
       */
      public Builder setPhoneCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *平台允许站点获取手机号code
       * </pre>
       *
       * <code>optional string phone_code = 1;</code>
       */
      public Builder clearPhoneCode() {
        
        phoneCode_ = getDefaultInstance().getPhoneCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *平台允许站点获取手机号code
       * </pre>
       *
       * <code>optional string phone_code = 1;</code>
       */
      public Builder setPhoneCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneCode_ = value;
        onChanged();
        return this;
      }

      private int expireTime_ ;
      /**
       * <pre>
       *code有效时间，单位s
       * </pre>
       *
       * <code>optional int32 expire_time = 2;</code>
       */
      public int getExpireTime() {
        return expireTime_;
      }
      /**
       * <pre>
       *code有效时间，单位s
       * </pre>
       *
       * <code>optional int32 expire_time = 2;</code>
       */
      public Builder setExpireTime(int value) {
        
        expireTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *code有效时间，单位s
       * </pre>
       *
       * <code>optional int32 expire_time = 2;</code>
       */
      public Builder clearExpireTime() {
        
        expireTime_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiPhoneApplyCodeResponse)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiPhoneApplyCodeResponse)
    private static final com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse();
    }

    public static com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPhoneApplyCodeResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiPhoneApplyCodeResponse>() {
      public ApiPhoneApplyCodeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiPhoneApplyCodeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPhoneApplyCodeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPhoneApplyCodeResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiPhoneApplyCodeProto.ApiPhoneApplyCodeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiPhoneApplyCodeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiPhoneApplyCodeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiPhoneApplyCodeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiPhoneApplyCodeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"platform/api_phone_applyCode.proto\022\010pl" +
      "atform\"+\n\030ApiPhoneApplyCodeRequest\022\017\n\007us" +
      "er_id\030\001 \001(\t\"D\n\031ApiPhoneApplyCodeResponse" +
      "\022\022\n\nphone_code\030\001 \001(\t\022\023\n\013expire_time\030\002 \001(" +
      "\0052p\n\030ApiPhoneApplyCodeService\022T\n\tapplyCo" +
      "de\022\".platform.ApiPhoneApplyCodeRequest\032#" +
      ".platform.ApiPhoneApplyCodeResponseB3\n\031c" +
      "om.akaxin.proto.platformB\026ApiPhoneApplyC" +
      "odeProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_platform_ApiPhoneApplyCodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_platform_ApiPhoneApplyCodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiPhoneApplyCodeRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_platform_ApiPhoneApplyCodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_platform_ApiPhoneApplyCodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiPhoneApplyCodeResponse_descriptor,
        new java.lang.String[] { "PhoneCode", "ExpireTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
