// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_platform_logout.proto

package com.akaxin.proto.platform;

public final class ApiPlatformLogoutProto {
  private ApiPlatformLogoutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiPlatformLogoutRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiPlatformLogoutRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 1;</code>
     */
    java.lang.String getUserIdPubk();
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();

    /**
     * <pre>
     *设备身份公钥
     * </pre>
     *
     * <code>optional string device_id_pubk = 2;</code>
     */
    java.lang.String getDeviceIdPubk();
    /**
     * <pre>
     *设备身份公钥
     * </pre>
     *
     * <code>optional string device_id_pubk = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdPubkBytes();
  }
  /**
   * Protobuf type {@code site.ApiPlatformLogoutRequest}
   */
  public  static final class ApiPlatformLogoutRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiPlatformLogoutRequest)
      ApiPlatformLogoutRequestOrBuilder {
    // Use ApiPlatformLogoutRequest.newBuilder() to construct.
    private ApiPlatformLogoutRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPlatformLogoutRequest() {
      userIdPubk_ = "";
      deviceIdPubk_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiPlatformLogoutRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPubk_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceIdPubk_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest.class, com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest.Builder.class);
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 1;
    private volatile java.lang.Object userIdPubk_;
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 1;</code>
     */
    public java.lang.String getUserIdPubk() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPubk_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_ID_PUBK_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceIdPubk_;
    /**
     * <pre>
     *设备身份公钥
     * </pre>
     *
     * <code>optional string device_id_pubk = 2;</code>
     */
    public java.lang.String getDeviceIdPubk() {
      java.lang.Object ref = deviceIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceIdPubk_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *设备身份公钥
     * </pre>
     *
     * <code>optional string device_id_pubk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdPubkBytes() {
      java.lang.Object ref = deviceIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdPubk_);
      }
      if (!getDeviceIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceIdPubk_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdPubk_);
      }
      if (!getDeviceIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceIdPubk_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest other = (com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest) obj;

      boolean result = true;
      result = result && getUserIdPubk()
          .equals(other.getUserIdPubk());
      result = result && getDeviceIdPubk()
          .equals(other.getDeviceIdPubk());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPubk().hashCode();
      hash = (37 * hash) + DEVICE_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceIdPubk().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiPlatformLogoutRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiPlatformLogoutRequest)
        com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest.class, com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userIdPubk_ = "";

        deviceIdPubk_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutRequest_descriptor;
      }

      public com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest build() {
        com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest buildPartial() {
        com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest result = new com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest(this);
        result.userIdPubk_ = userIdPubk_;
        result.deviceIdPubk_ = deviceIdPubk_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest) {
          return mergeFrom((com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest other) {
        if (other == com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest.getDefaultInstance()) return this;
        if (!other.getUserIdPubk().isEmpty()) {
          userIdPubk_ = other.userIdPubk_;
          onChanged();
        }
        if (!other.getDeviceIdPubk().isEmpty()) {
          deviceIdPubk_ = other.deviceIdPubk_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userIdPubk_ = "";
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public java.lang.String getUserIdPubk() {
        java.lang.Object ref = userIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        java.lang.Object ref = userIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder clearUserIdPubk() {
        
        userIdPubk_ = getDefaultInstance().getUserIdPubk();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceIdPubk_ = "";
      /**
       * <pre>
       *设备身份公钥
       * </pre>
       *
       * <code>optional string device_id_pubk = 2;</code>
       */
      public java.lang.String getDeviceIdPubk() {
        java.lang.Object ref = deviceIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *设备身份公钥
       * </pre>
       *
       * <code>optional string device_id_pubk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdPubkBytes() {
        java.lang.Object ref = deviceIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *设备身份公钥
       * </pre>
       *
       * <code>optional string device_id_pubk = 2;</code>
       */
      public Builder setDeviceIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备身份公钥
       * </pre>
       *
       * <code>optional string device_id_pubk = 2;</code>
       */
      public Builder clearDeviceIdPubk() {
        
        deviceIdPubk_ = getDefaultInstance().getDeviceIdPubk();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备身份公钥
       * </pre>
       *
       * <code>optional string device_id_pubk = 2;</code>
       */
      public Builder setDeviceIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceIdPubk_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiPlatformLogoutRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ApiPlatformLogoutRequest)
    private static final com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest();
    }

    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPlatformLogoutRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiPlatformLogoutRequest>() {
      public ApiPlatformLogoutRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiPlatformLogoutRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPlatformLogoutRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPlatformLogoutRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiPlatformLogoutResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiPlatformLogoutResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code site.ApiPlatformLogoutResponse}
   */
  public  static final class ApiPlatformLogoutResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiPlatformLogoutResponse)
      ApiPlatformLogoutResponseOrBuilder {
    // Use ApiPlatformLogoutResponse.newBuilder() to construct.
    private ApiPlatformLogoutResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPlatformLogoutResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiPlatformLogoutResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse.class, com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse other = (com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiPlatformLogoutResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiPlatformLogoutResponse)
        com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse.class, com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiPlatformLogoutProto.internal_static_site_ApiPlatformLogoutResponse_descriptor;
      }

      public com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse build() {
        com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse buildPartial() {
        com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse result = new com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse) {
          return mergeFrom((com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse other) {
        if (other == com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiPlatformLogoutResponse)
    }

    // @@protoc_insertion_point(class_scope:site.ApiPlatformLogoutResponse)
    private static final com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse();
    }

    public static com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPlatformLogoutResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiPlatformLogoutResponse>() {
      public ApiPlatformLogoutResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiPlatformLogoutResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPlatformLogoutResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPlatformLogoutResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiPlatformLogoutProto.ApiPlatformLogoutResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiPlatformLogoutRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiPlatformLogoutRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiPlatformLogoutResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiPlatformLogoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"platform/api_platform_logout.proto\022\004si" +
      "te\"H\n\030ApiPlatformLogoutRequest\022\024\n\014user_i" +
      "d_pubk\030\001 \001(\t\022\026\n\016device_id_pubk\030\002 \001(\t\"\033\n\031" +
      "ApiPlatformLogoutResponse2e\n\030ApiPlatform" +
      "LogoutService\022I\n\006logout\022\036.site.ApiPlatfo" +
      "rmLogoutRequest\032\037.site.ApiPlatformLogout" +
      "ResponseB3\n\031com.akaxin.proto.platformB\026A" +
      "piPlatformLogoutProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_site_ApiPlatformLogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ApiPlatformLogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiPlatformLogoutRequest_descriptor,
        new java.lang.String[] { "UserIdPubk", "DeviceIdPubk", });
    internal_static_site_ApiPlatformLogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_ApiPlatformLogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiPlatformLogoutResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
