// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_setting_deleteUserToken.proto

package com.akaxin.proto.platform;

public final class ApiSettingDeleteUserTokenProto {
  private ApiSettingDeleteUserTokenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiSettingDeleteUserTokenRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiSettingDeleteUserTokenRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *站点host
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    java.lang.String getSiteHost();
    /**
     * <pre>
     *站点host
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteHostBytes();

    /**
     * <pre>
     *站点port
     * </pre>
     *
     * <code>optional int32 site_port = 2;</code>
     */
    int getSitePort();
  }
  /**
   * Protobuf type {@code site.ApiSettingDeleteUserTokenRequest}
   */
  public  static final class ApiSettingDeleteUserTokenRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiSettingDeleteUserTokenRequest)
      ApiSettingDeleteUserTokenRequestOrBuilder {
    // Use ApiSettingDeleteUserTokenRequest.newBuilder() to construct.
    private ApiSettingDeleteUserTokenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiSettingDeleteUserTokenRequest() {
      siteHost_ = "";
      sitePort_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiSettingDeleteUserTokenRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              siteHost_ = s;
              break;
            }
            case 16: {

              sitePort_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest.class, com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest.Builder.class);
    }

    public static final int SITE_HOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object siteHost_;
    /**
     * <pre>
     *站点host
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    public java.lang.String getSiteHost() {
      java.lang.Object ref = siteHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteHost_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *站点host
     * </pre>
     *
     * <code>optional string site_host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteHostBytes() {
      java.lang.Object ref = siteHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_PORT_FIELD_NUMBER = 2;
    private int sitePort_;
    /**
     * <pre>
     *站点port
     * </pre>
     *
     * <code>optional int32 site_port = 2;</code>
     */
    public int getSitePort() {
      return sitePort_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSiteHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, siteHost_);
      }
      if (sitePort_ != 0) {
        output.writeInt32(2, sitePort_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSiteHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, siteHost_);
      }
      if (sitePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sitePort_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest other = (com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest) obj;

      boolean result = true;
      result = result && getSiteHost()
          .equals(other.getSiteHost());
      result = result && (getSitePort()
          == other.getSitePort());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SITE_HOST_FIELD_NUMBER;
      hash = (53 * hash) + getSiteHost().hashCode();
      hash = (37 * hash) + SITE_PORT_FIELD_NUMBER;
      hash = (53 * hash) + getSitePort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiSettingDeleteUserTokenRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiSettingDeleteUserTokenRequest)
        com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest.class, com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        siteHost_ = "";

        sitePort_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenRequest_descriptor;
      }

      public com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest build() {
        com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest buildPartial() {
        com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest result = new com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest(this);
        result.siteHost_ = siteHost_;
        result.sitePort_ = sitePort_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest) {
          return mergeFrom((com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest other) {
        if (other == com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest.getDefaultInstance()) return this;
        if (!other.getSiteHost().isEmpty()) {
          siteHost_ = other.siteHost_;
          onChanged();
        }
        if (other.getSitePort() != 0) {
          setSitePort(other.getSitePort());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object siteHost_ = "";
      /**
       * <pre>
       *站点host
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public java.lang.String getSiteHost() {
        java.lang.Object ref = siteHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *站点host
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteHostBytes() {
        java.lang.Object ref = siteHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *站点host
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public Builder setSiteHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点host
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public Builder clearSiteHost() {
        
        siteHost_ = getDefaultInstance().getSiteHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点host
       * </pre>
       *
       * <code>optional string site_host = 1;</code>
       */
      public Builder setSiteHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteHost_ = value;
        onChanged();
        return this;
      }

      private int sitePort_ ;
      /**
       * <pre>
       *站点port
       * </pre>
       *
       * <code>optional int32 site_port = 2;</code>
       */
      public int getSitePort() {
        return sitePort_;
      }
      /**
       * <pre>
       *站点port
       * </pre>
       *
       * <code>optional int32 site_port = 2;</code>
       */
      public Builder setSitePort(int value) {
        
        sitePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *站点port
       * </pre>
       *
       * <code>optional int32 site_port = 2;</code>
       */
      public Builder clearSitePort() {
        
        sitePort_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiSettingDeleteUserTokenRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ApiSettingDeleteUserTokenRequest)
    private static final com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest();
    }

    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiSettingDeleteUserTokenRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiSettingDeleteUserTokenRequest>() {
      public ApiSettingDeleteUserTokenRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiSettingDeleteUserTokenRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiSettingDeleteUserTokenRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiSettingDeleteUserTokenRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiSettingDeleteUserTokenResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiSettingDeleteUserTokenResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code site.ApiSettingDeleteUserTokenResponse}
   */
  public  static final class ApiSettingDeleteUserTokenResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiSettingDeleteUserTokenResponse)
      ApiSettingDeleteUserTokenResponseOrBuilder {
    // Use ApiSettingDeleteUserTokenResponse.newBuilder() to construct.
    private ApiSettingDeleteUserTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiSettingDeleteUserTokenResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiSettingDeleteUserTokenResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse.class, com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse other = (com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiSettingDeleteUserTokenResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiSettingDeleteUserTokenResponse)
        com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse.class, com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.internal_static_site_ApiSettingDeleteUserTokenResponse_descriptor;
      }

      public com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse build() {
        com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse buildPartial() {
        com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse result = new com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse) {
          return mergeFrom((com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse other) {
        if (other == com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiSettingDeleteUserTokenResponse)
    }

    // @@protoc_insertion_point(class_scope:site.ApiSettingDeleteUserTokenResponse)
    private static final com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse();
    }

    public static com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiSettingDeleteUserTokenResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiSettingDeleteUserTokenResponse>() {
      public ApiSettingDeleteUserTokenResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiSettingDeleteUserTokenResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiSettingDeleteUserTokenResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiSettingDeleteUserTokenResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiSettingDeleteUserTokenProto.ApiSettingDeleteUserTokenResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiSettingDeleteUserTokenRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiSettingDeleteUserTokenRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiSettingDeleteUserTokenResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiSettingDeleteUserTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*platform/api_setting_deleteUserToken.p" +
      "roto\022\004site\"H\n ApiSettingDeleteUserTokenR" +
      "equest\022\021\n\tsite_host\030\001 \001(\t\022\021\n\tsite_port\030\002" +
      " \001(\005\"#\n!ApiSettingDeleteUserTokenRespons" +
      "e2\206\001\n ApiSettingDeleteUserTokenService\022b" +
      "\n\017deleteUserToken\022&.site.ApiSettingDelet" +
      "eUserTokenRequest\032\'.site.ApiSettingDelet" +
      "eUserTokenResponseB;\n\031com.akaxin.proto.p" +
      "latformB\036ApiSettingDeleteUserTokenProtob" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_site_ApiSettingDeleteUserTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ApiSettingDeleteUserTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiSettingDeleteUserTokenRequest_descriptor,
        new java.lang.String[] { "SiteHost", "SitePort", });
    internal_static_site_ApiSettingDeleteUserTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_ApiSettingDeleteUserTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiSettingDeleteUserTokenResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
