// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_user_upload.proto

package com.akaxin.proto.platform;

public final class ApiUserUploadProto {
  private ApiUserUploadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiUserUploadRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiUserUploadRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    java.lang.String getUserIdPrik();
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPrikBytes();

    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    java.lang.String getUserIdPubk();
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();

    /**
     * <pre>
     *用户个人头像
     * </pre>
     *
     * <code>optional string user_photo = 3;</code>
     */
    java.lang.String getUserPhoto();
    /**
     * <pre>
     *用户个人头像
     * </pre>
     *
     * <code>optional string user_photo = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserPhotoBytes();

    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>optional string user_name = 4;</code>
     */
    java.lang.String getUserName();
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>optional string user_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 5;</code>
     */
    java.lang.String getPhoneId();
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getPhoneIdBytes();

    /**
     * <pre>
     *客户端类型 IOS／Andorid
     * </pre>
     *
     * <code>optional string client_type = 6;</code>
     */
    java.lang.String getClientType();
    /**
     * <pre>
     *客户端类型 IOS／Andorid
     * </pre>
     *
     * <code>optional string client_type = 6;</code>
     */
    com.google.protobuf.ByteString
        getClientTypeBytes();

    /**
     * <pre>
     *手机Rom
     * </pre>
     *
     * <code>optional string rom = 7;</code>
     */
    java.lang.String getRom();
    /**
     * <pre>
     *手机Rom
     * </pre>
     *
     * <code>optional string rom = 7;</code>
     */
    com.google.protobuf.ByteString
        getRomBytes();

    /**
     * <pre>
     *push发送需要的token
     * </pre>
     *
     * <code>optional string push_token = 8;</code>
     */
    java.lang.String getPushToken();
    /**
     * <pre>
     *push发送需要的token
     * </pre>
     *
     * <code>optional string push_token = 8;</code>
     */
    com.google.protobuf.ByteString
        getPushTokenBytes();
  }
  /**
   * Protobuf type {@code platform.ApiUserUploadRequest}
   */
  public  static final class ApiUserUploadRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiUserUploadRequest)
      ApiUserUploadRequestOrBuilder {
    // Use ApiUserUploadRequest.newBuilder() to construct.
    private ApiUserUploadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiUserUploadRequest() {
      userIdPrik_ = "";
      userIdPubk_ = "";
      userPhoto_ = "";
      userName_ = "";
      phoneId_ = "";
      clientType_ = "";
      rom_ = "";
      pushToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiUserUploadRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPrik_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPubk_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userPhoto_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneId_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              clientType_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              rom_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              pushToken_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest.class, com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest.Builder.class);
    }

    public static final int USER_ID_PRIK_FIELD_NUMBER = 1;
    private volatile java.lang.Object userIdPrik_;
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    public java.lang.String getUserIdPrik() {
      java.lang.Object ref = userIdPrik_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPrik_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPrikBytes() {
      java.lang.Object ref = userIdPrik_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPrik_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 2;
    private volatile java.lang.Object userIdPubk_;
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    public java.lang.String getUserIdPubk() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPubk_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_PHOTO_FIELD_NUMBER = 3;
    private volatile java.lang.Object userPhoto_;
    /**
     * <pre>
     *用户个人头像
     * </pre>
     *
     * <code>optional string user_photo = 3;</code>
     */
    public java.lang.String getUserPhoto() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhoto_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户个人头像
     * </pre>
     *
     * <code>optional string user_photo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserPhotoBytes() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>optional string user_name = 4;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>optional string user_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object phoneId_;
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 5;</code>
     */
    public java.lang.String getPhoneId() {
      java.lang.Object ref = phoneId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户手机号码
     * </pre>
     *
     * <code>optional string phone_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneIdBytes() {
      java.lang.Object ref = phoneId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object clientType_;
    /**
     * <pre>
     *客户端类型 IOS／Andorid
     * </pre>
     *
     * <code>optional string client_type = 6;</code>
     */
    public java.lang.String getClientType() {
      java.lang.Object ref = clientType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户端类型 IOS／Andorid
     * </pre>
     *
     * <code>optional string client_type = 6;</code>
     */
    public com.google.protobuf.ByteString
        getClientTypeBytes() {
      java.lang.Object ref = clientType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROM_FIELD_NUMBER = 7;
    private volatile java.lang.Object rom_;
    /**
     * <pre>
     *手机Rom
     * </pre>
     *
     * <code>optional string rom = 7;</code>
     */
    public java.lang.String getRom() {
      java.lang.Object ref = rom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rom_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *手机Rom
     * </pre>
     *
     * <code>optional string rom = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRomBytes() {
      java.lang.Object ref = rom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUSH_TOKEN_FIELD_NUMBER = 8;
    private volatile java.lang.Object pushToken_;
    /**
     * <pre>
     *push发送需要的token
     * </pre>
     *
     * <code>optional string push_token = 8;</code>
     */
    public java.lang.String getPushToken() {
      java.lang.Object ref = pushToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pushToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *push发送需要的token
     * </pre>
     *
     * <code>optional string push_token = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPushTokenBytes() {
      java.lang.Object ref = pushToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pushToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdPrikBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdPrik_);
      }
      if (!getUserIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userIdPubk_);
      }
      if (!getUserPhotoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPhoto_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userName_);
      }
      if (!getPhoneIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, phoneId_);
      }
      if (!getClientTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clientType_);
      }
      if (!getRomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, rom_);
      }
      if (!getPushTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pushToken_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdPrikBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdPrik_);
      }
      if (!getUserIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userIdPubk_);
      }
      if (!getUserPhotoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPhoto_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userName_);
      }
      if (!getPhoneIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, phoneId_);
      }
      if (!getClientTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clientType_);
      }
      if (!getRomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, rom_);
      }
      if (!getPushTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pushToken_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest other = (com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest) obj;

      boolean result = true;
      result = result && getUserIdPrik()
          .equals(other.getUserIdPrik());
      result = result && getUserIdPubk()
          .equals(other.getUserIdPubk());
      result = result && getUserPhoto()
          .equals(other.getUserPhoto());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getPhoneId()
          .equals(other.getPhoneId());
      result = result && getClientType()
          .equals(other.getClientType());
      result = result && getRom()
          .equals(other.getRom());
      result = result && getPushToken()
          .equals(other.getPushToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_PRIK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPrik().hashCode();
      hash = (37 * hash) + USER_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPubk().hashCode();
      hash = (37 * hash) + USER_PHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getUserPhoto().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + PHONE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneId().hashCode();
      hash = (37 * hash) + CLIENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getClientType().hashCode();
      hash = (37 * hash) + ROM_FIELD_NUMBER;
      hash = (53 * hash) + getRom().hashCode();
      hash = (37 * hash) + PUSH_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getPushToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiUserUploadRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiUserUploadRequest)
        com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest.class, com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userIdPrik_ = "";

        userIdPubk_ = "";

        userPhoto_ = "";

        userName_ = "";

        phoneId_ = "";

        clientType_ = "";

        rom_ = "";

        pushToken_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadRequest_descriptor;
      }

      public com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest build() {
        com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest buildPartial() {
        com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest result = new com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest(this);
        result.userIdPrik_ = userIdPrik_;
        result.userIdPubk_ = userIdPubk_;
        result.userPhoto_ = userPhoto_;
        result.userName_ = userName_;
        result.phoneId_ = phoneId_;
        result.clientType_ = clientType_;
        result.rom_ = rom_;
        result.pushToken_ = pushToken_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest) {
          return mergeFrom((com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest other) {
        if (other == com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest.getDefaultInstance()) return this;
        if (!other.getUserIdPrik().isEmpty()) {
          userIdPrik_ = other.userIdPrik_;
          onChanged();
        }
        if (!other.getUserIdPubk().isEmpty()) {
          userIdPubk_ = other.userIdPubk_;
          onChanged();
        }
        if (!other.getUserPhoto().isEmpty()) {
          userPhoto_ = other.userPhoto_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getPhoneId().isEmpty()) {
          phoneId_ = other.phoneId_;
          onChanged();
        }
        if (!other.getClientType().isEmpty()) {
          clientType_ = other.clientType_;
          onChanged();
        }
        if (!other.getRom().isEmpty()) {
          rom_ = other.rom_;
          onChanged();
        }
        if (!other.getPushToken().isEmpty()) {
          pushToken_ = other.pushToken_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userIdPrik_ = "";
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public java.lang.String getUserIdPrik() {
        java.lang.Object ref = userIdPrik_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPrik_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPrikBytes() {
        java.lang.Object ref = userIdPrik_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPrik_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder setUserIdPrik(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPrik_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder clearUserIdPrik() {
        
        userIdPrik_ = getDefaultInstance().getUserIdPrik();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder setUserIdPrikBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPrik_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userIdPubk_ = "";
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public java.lang.String getUserIdPubk() {
        java.lang.Object ref = userIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        java.lang.Object ref = userIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder setUserIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder clearUserIdPubk() {
        
        userIdPubk_ = getDefaultInstance().getUserIdPubk();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPhoto_ = "";
      /**
       * <pre>
       *用户个人头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public java.lang.String getUserPhoto() {
        java.lang.Object ref = userPhoto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPhoto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户个人头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserPhotoBytes() {
        java.lang.Object ref = userPhoto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPhoto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户个人头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public Builder setUserPhoto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPhoto_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户个人头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public Builder clearUserPhoto() {
        
        userPhoto_ = getDefaultInstance().getUserPhoto();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户个人头像
       * </pre>
       *
       * <code>optional string user_photo = 3;</code>
       */
      public Builder setUserPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPhoto_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>optional string user_name = 4;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>optional string user_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>optional string user_name = 4;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>optional string user_name = 4;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>optional string user_name = 4;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneId_ = "";
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 5;</code>
       */
      public java.lang.String getPhoneId() {
        java.lang.Object ref = phoneId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneIdBytes() {
        java.lang.Object ref = phoneId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 5;</code>
       */
      public Builder setPhoneId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 5;</code>
       */
      public Builder clearPhoneId() {
        
        phoneId_ = getDefaultInstance().getPhoneId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户手机号码
       * </pre>
       *
       * <code>optional string phone_id = 5;</code>
       */
      public Builder setPhoneIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientType_ = "";
      /**
       * <pre>
       *客户端类型 IOS／Andorid
       * </pre>
       *
       * <code>optional string client_type = 6;</code>
       */
      public java.lang.String getClientType() {
        java.lang.Object ref = clientType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端类型 IOS／Andorid
       * </pre>
       *
       * <code>optional string client_type = 6;</code>
       */
      public com.google.protobuf.ByteString
          getClientTypeBytes() {
        java.lang.Object ref = clientType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端类型 IOS／Andorid
       * </pre>
       *
       * <code>optional string client_type = 6;</code>
       */
      public Builder setClientType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端类型 IOS／Andorid
       * </pre>
       *
       * <code>optional string client_type = 6;</code>
       */
      public Builder clearClientType() {
        
        clientType_ = getDefaultInstance().getClientType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端类型 IOS／Andorid
       * </pre>
       *
       * <code>optional string client_type = 6;</code>
       */
      public Builder setClientTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rom_ = "";
      /**
       * <pre>
       *手机Rom
       * </pre>
       *
       * <code>optional string rom = 7;</code>
       */
      public java.lang.String getRom() {
        java.lang.Object ref = rom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *手机Rom
       * </pre>
       *
       * <code>optional string rom = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRomBytes() {
        java.lang.Object ref = rom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机Rom
       * </pre>
       *
       * <code>optional string rom = 7;</code>
       */
      public Builder setRom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rom_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机Rom
       * </pre>
       *
       * <code>optional string rom = 7;</code>
       */
      public Builder clearRom() {
        
        rom_ = getDefaultInstance().getRom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机Rom
       * </pre>
       *
       * <code>optional string rom = 7;</code>
       */
      public Builder setRomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pushToken_ = "";
      /**
       * <pre>
       *push发送需要的token
       * </pre>
       *
       * <code>optional string push_token = 8;</code>
       */
      public java.lang.String getPushToken() {
        java.lang.Object ref = pushToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pushToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *push发送需要的token
       * </pre>
       *
       * <code>optional string push_token = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPushTokenBytes() {
        java.lang.Object ref = pushToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pushToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *push发送需要的token
       * </pre>
       *
       * <code>optional string push_token = 8;</code>
       */
      public Builder setPushToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pushToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *push发送需要的token
       * </pre>
       *
       * <code>optional string push_token = 8;</code>
       */
      public Builder clearPushToken() {
        
        pushToken_ = getDefaultInstance().getPushToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *push发送需要的token
       * </pre>
       *
       * <code>optional string push_token = 8;</code>
       */
      public Builder setPushTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pushToken_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiUserUploadRequest)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiUserUploadRequest)
    private static final com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest();
    }

    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiUserUploadRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiUserUploadRequest>() {
      public ApiUserUploadRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiUserUploadRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiUserUploadRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiUserUploadRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiUserUploadResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiUserUploadResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code platform.ApiUserUploadResponse}
   */
  public  static final class ApiUserUploadResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiUserUploadResponse)
      ApiUserUploadResponseOrBuilder {
    // Use ApiUserUploadResponse.newBuilder() to construct.
    private ApiUserUploadResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiUserUploadResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiUserUploadResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse.class, com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse other = (com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiUserUploadResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiUserUploadResponse)
        com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse.class, com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiUserUploadProto.internal_static_platform_ApiUserUploadResponse_descriptor;
      }

      public com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse build() {
        com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse buildPartial() {
        com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse result = new com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse) {
          return mergeFrom((com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse other) {
        if (other == com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiUserUploadResponse)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiUserUploadResponse)
    private static final com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse();
    }

    public static com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiUserUploadResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiUserUploadResponse>() {
      public ApiUserUploadResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiUserUploadResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiUserUploadResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiUserUploadResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiUserUploadProto.ApiUserUploadResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiUserUploadRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiUserUploadRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiUserUploadResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiUserUploadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036platform/api_user_upload.proto\022\010platfo" +
      "rm\"\261\001\n\024ApiUserUploadRequest\022\024\n\014user_id_p" +
      "rik\030\001 \001(\t\022\024\n\014user_id_pubk\030\002 \001(\t\022\022\n\nuser_" +
      "photo\030\003 \001(\t\022\021\n\tuser_name\030\004 \001(\t\022\020\n\010phone_" +
      "id\030\005 \001(\t\022\023\n\013client_type\030\006 \001(\t\022\013\n\003rom\030\007 \001" +
      "(\t\022\022\n\npush_token\030\010 \001(\t\"\027\n\025ApiUserUploadR" +
      "esponse2a\n\024ApiUserUploadService\022I\n\006uploa" +
      "d\022\036.platform.ApiUserUploadRequest\032\037.plat" +
      "form.ApiUserUploadResponseB/\n\031com.akaxin" +
      ".proto.platformB\022ApiUserUploadProtob\006pro",
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_platform_ApiUserUploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_platform_ApiUserUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiUserUploadRequest_descriptor,
        new java.lang.String[] { "UserIdPrik", "UserIdPubk", "UserPhoto", "UserName", "PhoneId", "ClientType", "Rom", "PushToken", });
    internal_static_platform_ApiUserUploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_platform_ApiUserUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiUserUploadResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
