// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_user_realName.proto

package com.akaxin.proto.platform;

public final class ApiUserRealNameProto {
  private ApiUserRealNameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiUserRealNameRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiUserRealNameRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    java.lang.String getUserIdPrik();
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPrikBytes();

    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    java.lang.String getUserIdPubk();
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();

    /**
     * <pre>
     *绑定的手机号码
     * </pre>
     *
     * <code>optional string phone_id = 3;</code>
     */
    java.lang.String getPhoneId();
    /**
     * <pre>
     *绑定的手机号码
     * </pre>
     *
     * <code>optional string phone_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhoneIdBytes();

    /**
     * <pre>
     *手机验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 4;</code>
     */
    java.lang.String getPhoneVerifyCode();
    /**
     * <pre>
     *手机验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 4;</code>
     */
    com.google.protobuf.ByteString
        getPhoneVerifyCodeBytes();

    /**
     * <pre>
     *绑定手机登陆密码
     * </pre>
     *
     * <code>optional string password = 5;</code>
     */
    java.lang.String getPassword();
    /**
     * <pre>
     *绑定手机登陆密码
     * </pre>
     *
     * <code>optional string password = 5;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <pre>
     *国际区号
     * </pre>
     *
     * <code>optional string global_roaming = 6;</code>
     */
    java.lang.String getGlobalRoaming();
    /**
     * <pre>
     *国际区号
     * </pre>
     *
     * <code>optional string global_roaming = 6;</code>
     */
    com.google.protobuf.ByteString
        getGlobalRoamingBytes();
  }
  /**
   * Protobuf type {@code platform.ApiUserRealNameRequest}
   */
  public  static final class ApiUserRealNameRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiUserRealNameRequest)
      ApiUserRealNameRequestOrBuilder {
    // Use ApiUserRealNameRequest.newBuilder() to construct.
    private ApiUserRealNameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiUserRealNameRequest() {
      userIdPrik_ = "";
      userIdPubk_ = "";
      phoneId_ = "";
      phoneVerifyCode_ = "";
      password_ = "";
      globalRoaming_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiUserRealNameRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPrik_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPubk_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneVerifyCode_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              globalRoaming_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest.class, com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest.Builder.class);
    }

    public static final int USER_ID_PRIK_FIELD_NUMBER = 1;
    private volatile java.lang.Object userIdPrik_;
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    public java.lang.String getUserIdPrik() {
      java.lang.Object ref = userIdPrik_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPrik_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户身份私钥
     * </pre>
     *
     * <code>optional string user_id_prik = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPrikBytes() {
      java.lang.Object ref = userIdPrik_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPrik_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 2;
    private volatile java.lang.Object userIdPubk_;
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    public java.lang.String getUserIdPubk() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPubk_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户身份公钥
     * </pre>
     *
     * <code>optional string user_id_pubk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object phoneId_;
    /**
     * <pre>
     *绑定的手机号码
     * </pre>
     *
     * <code>optional string phone_id = 3;</code>
     */
    public java.lang.String getPhoneId() {
      java.lang.Object ref = phoneId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *绑定的手机号码
     * </pre>
     *
     * <code>optional string phone_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneIdBytes() {
      java.lang.Object ref = phoneId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_VERIFY_CODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object phoneVerifyCode_;
    /**
     * <pre>
     *手机验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 4;</code>
     */
    public java.lang.String getPhoneVerifyCode() {
      java.lang.Object ref = phoneVerifyCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneVerifyCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *手机验证码
     * </pre>
     *
     * <code>optional string phone_verify_code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneVerifyCodeBytes() {
      java.lang.Object ref = phoneVerifyCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneVerifyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 5;
    private volatile java.lang.Object password_;
    /**
     * <pre>
     *绑定手机登陆密码
     * </pre>
     *
     * <code>optional string password = 5;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *绑定手机登陆密码
     * </pre>
     *
     * <code>optional string password = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GLOBAL_ROAMING_FIELD_NUMBER = 6;
    private volatile java.lang.Object globalRoaming_;
    /**
     * <pre>
     *国际区号
     * </pre>
     *
     * <code>optional string global_roaming = 6;</code>
     */
    public java.lang.String getGlobalRoaming() {
      java.lang.Object ref = globalRoaming_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        globalRoaming_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *国际区号
     * </pre>
     *
     * <code>optional string global_roaming = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGlobalRoamingBytes() {
      java.lang.Object ref = globalRoaming_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        globalRoaming_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdPrikBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdPrik_);
      }
      if (!getUserIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userIdPubk_);
      }
      if (!getPhoneIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneId_);
      }
      if (!getPhoneVerifyCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phoneVerifyCode_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, password_);
      }
      if (!getGlobalRoamingBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, globalRoaming_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdPrikBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdPrik_);
      }
      if (!getUserIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userIdPubk_);
      }
      if (!getPhoneIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneId_);
      }
      if (!getPhoneVerifyCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phoneVerifyCode_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, password_);
      }
      if (!getGlobalRoamingBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, globalRoaming_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest other = (com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest) obj;

      boolean result = true;
      result = result && getUserIdPrik()
          .equals(other.getUserIdPrik());
      result = result && getUserIdPubk()
          .equals(other.getUserIdPubk());
      result = result && getPhoneId()
          .equals(other.getPhoneId());
      result = result && getPhoneVerifyCode()
          .equals(other.getPhoneVerifyCode());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && getGlobalRoaming()
          .equals(other.getGlobalRoaming());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_PRIK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPrik().hashCode();
      hash = (37 * hash) + USER_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPubk().hashCode();
      hash = (37 * hash) + PHONE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneId().hashCode();
      hash = (37 * hash) + PHONE_VERIFY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneVerifyCode().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + GLOBAL_ROAMING_FIELD_NUMBER;
      hash = (53 * hash) + getGlobalRoaming().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiUserRealNameRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiUserRealNameRequest)
        com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest.class, com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userIdPrik_ = "";

        userIdPubk_ = "";

        phoneId_ = "";

        phoneVerifyCode_ = "";

        password_ = "";

        globalRoaming_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameRequest_descriptor;
      }

      public com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest build() {
        com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest buildPartial() {
        com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest result = new com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest(this);
        result.userIdPrik_ = userIdPrik_;
        result.userIdPubk_ = userIdPubk_;
        result.phoneId_ = phoneId_;
        result.phoneVerifyCode_ = phoneVerifyCode_;
        result.password_ = password_;
        result.globalRoaming_ = globalRoaming_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest) {
          return mergeFrom((com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest other) {
        if (other == com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest.getDefaultInstance()) return this;
        if (!other.getUserIdPrik().isEmpty()) {
          userIdPrik_ = other.userIdPrik_;
          onChanged();
        }
        if (!other.getUserIdPubk().isEmpty()) {
          userIdPubk_ = other.userIdPubk_;
          onChanged();
        }
        if (!other.getPhoneId().isEmpty()) {
          phoneId_ = other.phoneId_;
          onChanged();
        }
        if (!other.getPhoneVerifyCode().isEmpty()) {
          phoneVerifyCode_ = other.phoneVerifyCode_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getGlobalRoaming().isEmpty()) {
          globalRoaming_ = other.globalRoaming_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userIdPrik_ = "";
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public java.lang.String getUserIdPrik() {
        java.lang.Object ref = userIdPrik_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPrik_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPrikBytes() {
        java.lang.Object ref = userIdPrik_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPrik_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder setUserIdPrik(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPrik_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder clearUserIdPrik() {
        
        userIdPrik_ = getDefaultInstance().getUserIdPrik();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份私钥
       * </pre>
       *
       * <code>optional string user_id_prik = 1;</code>
       */
      public Builder setUserIdPrikBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPrik_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userIdPubk_ = "";
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public java.lang.String getUserIdPubk() {
        java.lang.Object ref = userIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        java.lang.Object ref = userIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder setUserIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder clearUserIdPubk() {
        
        userIdPubk_ = getDefaultInstance().getUserIdPubk();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥
       * </pre>
       *
       * <code>optional string user_id_pubk = 2;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneId_ = "";
      /**
       * <pre>
       *绑定的手机号码
       * </pre>
       *
       * <code>optional string phone_id = 3;</code>
       */
      public java.lang.String getPhoneId() {
        java.lang.Object ref = phoneId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *绑定的手机号码
       * </pre>
       *
       * <code>optional string phone_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneIdBytes() {
        java.lang.Object ref = phoneId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *绑定的手机号码
       * </pre>
       *
       * <code>optional string phone_id = 3;</code>
       */
      public Builder setPhoneId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定的手机号码
       * </pre>
       *
       * <code>optional string phone_id = 3;</code>
       */
      public Builder clearPhoneId() {
        
        phoneId_ = getDefaultInstance().getPhoneId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定的手机号码
       * </pre>
       *
       * <code>optional string phone_id = 3;</code>
       */
      public Builder setPhoneIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneVerifyCode_ = "";
      /**
       * <pre>
       *手机验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 4;</code>
       */
      public java.lang.String getPhoneVerifyCode() {
        java.lang.Object ref = phoneVerifyCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneVerifyCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *手机验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneVerifyCodeBytes() {
        java.lang.Object ref = phoneVerifyCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneVerifyCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 4;</code>
       */
      public Builder setPhoneVerifyCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneVerifyCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 4;</code>
       */
      public Builder clearPhoneVerifyCode() {
        
        phoneVerifyCode_ = getDefaultInstance().getPhoneVerifyCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机验证码
       * </pre>
       *
       * <code>optional string phone_verify_code = 4;</code>
       */
      public Builder setPhoneVerifyCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneVerifyCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <pre>
       *绑定手机登陆密码
       * </pre>
       *
       * <code>optional string password = 5;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *绑定手机登陆密码
       * </pre>
       *
       * <code>optional string password = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *绑定手机登陆密码
       * </pre>
       *
       * <code>optional string password = 5;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定手机登陆密码
       * </pre>
       *
       * <code>optional string password = 5;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *绑定手机登陆密码
       * </pre>
       *
       * <code>optional string password = 5;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object globalRoaming_ = "";
      /**
       * <pre>
       *国际区号
       * </pre>
       *
       * <code>optional string global_roaming = 6;</code>
       */
      public java.lang.String getGlobalRoaming() {
        java.lang.Object ref = globalRoaming_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          globalRoaming_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *国际区号
       * </pre>
       *
       * <code>optional string global_roaming = 6;</code>
       */
      public com.google.protobuf.ByteString
          getGlobalRoamingBytes() {
        java.lang.Object ref = globalRoaming_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          globalRoaming_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *国际区号
       * </pre>
       *
       * <code>optional string global_roaming = 6;</code>
       */
      public Builder setGlobalRoaming(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        globalRoaming_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *国际区号
       * </pre>
       *
       * <code>optional string global_roaming = 6;</code>
       */
      public Builder clearGlobalRoaming() {
        
        globalRoaming_ = getDefaultInstance().getGlobalRoaming();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *国际区号
       * </pre>
       *
       * <code>optional string global_roaming = 6;</code>
       */
      public Builder setGlobalRoamingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        globalRoaming_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiUserRealNameRequest)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiUserRealNameRequest)
    private static final com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest();
    }

    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiUserRealNameRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiUserRealNameRequest>() {
      public ApiUserRealNameRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiUserRealNameRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiUserRealNameRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiUserRealNameRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiUserRealNameResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiUserRealNameResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code platform.ApiUserRealNameResponse}
   */
  public  static final class ApiUserRealNameResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiUserRealNameResponse)
      ApiUserRealNameResponseOrBuilder {
    // Use ApiUserRealNameResponse.newBuilder() to construct.
    private ApiUserRealNameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiUserRealNameResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiUserRealNameResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse.class, com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse other = (com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiUserRealNameResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiUserRealNameResponse)
        com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse.class, com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.platform.ApiUserRealNameProto.internal_static_platform_ApiUserRealNameResponse_descriptor;
      }

      public com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse getDefaultInstanceForType() {
        return com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse.getDefaultInstance();
      }

      public com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse build() {
        com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse buildPartial() {
        com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse result = new com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse) {
          return mergeFrom((com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse other) {
        if (other == com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiUserRealNameResponse)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiUserRealNameResponse)
    private static final com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse();
    }

    public static com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiUserRealNameResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiUserRealNameResponse>() {
      public ApiUserRealNameResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiUserRealNameResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiUserRealNameResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiUserRealNameResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.platform.ApiUserRealNameProto.ApiUserRealNameResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiUserRealNameRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiUserRealNameRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiUserRealNameResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiUserRealNameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n platform/api_user_realName.proto\022\010plat" +
      "form\"\233\001\n\026ApiUserRealNameRequest\022\024\n\014user_" +
      "id_prik\030\001 \001(\t\022\024\n\014user_id_pubk\030\002 \001(\t\022\020\n\010p" +
      "hone_id\030\003 \001(\t\022\031\n\021phone_verify_code\030\004 \001(\t" +
      "\022\020\n\010password\030\005 \001(\t\022\026\n\016global_roaming\030\006 \001" +
      "(\t\"\031\n\027ApiUserRealNameResponse2i\n\026ApiUser" +
      "RealNameService\022O\n\010realName\022 .platform.A" +
      "piUserRealNameRequest\032!.platform.ApiUser" +
      "RealNameResponseB1\n\031com.akaxin.proto.pla" +
      "tformB\024ApiUserRealNameProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_platform_ApiUserRealNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_platform_ApiUserRealNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiUserRealNameRequest_descriptor,
        new java.lang.String[] { "UserIdPrik", "UserIdPubk", "PhoneId", "PhoneVerifyCode", "Password", "GlobalRoaming", });
    internal_static_platform_ApiUserRealNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_platform_ApiUserRealNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiUserRealNameResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
